- name: Check if buildset URL exists
  uri:
    url: "{{ buildset_artifacts_url }}/{{ current_tag }}"
    validate_certs: no
  register: webpage  
  ignore_errors: true

- name: Set DLRN API url based on current tag
  shell:
    cmd: |
      if [[ "{{ current_tag }}" =~ -uc ]]; then
          baseurl="https://dlrn-zuul.jpena.net/api-centos-master-uc"
      else
        # This is a stable release
          baseurl="https://dlrn-zuul.jpena.net/api-centos-{{ current_tag }}"
      fi
      echo $baseurl
  register: dlrnapi_url
  when: webpage.status == 200

- name: Import commit
  shell:
    cmd: |
      . {{ zuul.executor.work_root }}/.venv/bin/activate
      dlrnapi --url {{ dlrnapi_url.stdout }} --username ciuser commit-import --repo-url {{ buildset_artifacts_url }}/{{ current_tag }}/repos/current/
  environment:
      DLRNAPI_PASSWORD: "{{ dlrnapi_creds.password }}"
  when: webpage.status == 200
