- secret:
    name: site_install_server
    data:
      fqdn: managesf.sftests.com
      ssh_known_hosts: managesf.sftests.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgoQM+01Q9jpT78UkyZQF4Qso/yI9Cp9SY2sGUsusODgDmCFc/BTe48BLCjNoV9KqRIk8D2VV1FX1EuLwGMu5q0V/e0craegKafWx+/F9GKWVE/e1X3QcqIF76LAG5XcYCzUV9G44FdeOIUJfRvaxI1dxww2AZCMgGxDQBXcf2Oafnr4z/TB6I2CBTm7daLh80jKMXFpmCsq+egRk6C/Uer7wa5pTMbgsQDc8chY7zVUOElnjvNlwZmKVTGRf4WULDFA2Tr24SJs7kv0PdT21PeoB+v31qEsLwTmbIWTqFWi8J1Gj6GEhD1CzxmI8aAQLPAwzDJs8zXiL1OwWWU3RX
      ssh_username: root
      ssh_private_key: !encrypted/pkcs1-oaep
        - TtQFWqQsvy2Gt3gg9kaMiyIcFeP4FAuV1ni9C5oWPd1cPQSw4AD6By6sTiVJvJbpBPnj/
          hwsn8rX3k2Wucbo9y2LxWvRmkRlkWT820uFDjBfPAmTeK29i5x5VLmkL7I9YDgwogjUjb
          tm4vJSv99rPoWSQrngLQ8f1sNH4HIV0ObrbEceFRw4b5Oy0EhF8DPXMmRO1mspQY1CGHd
          N8kSwhY9gRyHk6/dGNkblhWXLm/VJsC5+hSJ+Otv078vKPOJ60C4ujeZ3m8Y/G5LLmHAe
          dyAhQSDqo5BSgAvCk0x7SGpb9A9IZlwZoHJWezXpOvoP2P37l9mDejqsgp5/U2fvcUdDM
          jNTNef7vWx9NXd1TciKOzXjiOMbEoFhHeBGpoXH0WkxMxonQdaw2W7xftE9flCalqEPkg
          g6sCKdNlMyGIYPnhYTDlcddI+c6PttGaHp2O8lHa43aOo877reBxTwn+kw2UEVtWVIPE2
          W256E0pCI5RHcqd7KoestoHMOV+c+Er9nkWK4/OUD0cehJKHUqyeRlMor8lQATgEmTHo4
          9LBD7NFHIFYwE28kkwdhJMNoD9L1LMruA/Y7vmd0d+uzUHKYb9d76ISaZj3q4IRwxqxx2
          PyNHe12i59nSzw9s/KPXh0gyrgpPNyq4cMwlRXrD7e8amVyyO3QgbWVGyBj8tY=
        - bQ97U6LQnqdc/C0yCI/vYqwOQjUk/dA8aBSbjT4AQJHRNXSCLnLDCJz9VW5U70MvFHuiC
          cmBGh4NGgCMVBQSlJpu1+cTDjQ316zdd3bNhjYQDL/U54gMjaG/HF1Ho9zgWwe8sP6ydL
          CzBYw9BpKCmtpjM4ReccQCPbF4JsDvDxW3hNWDRfwZ4pq8A0cZ7pLajFyfJFOveuTRlGD
          V58r3HGzAoseaEYMXd/ZOgWV/KhSAY3gT8y8kUSUk0ocJygFrEhe58fQ0MB3L5cq31JRF
          wmLPxZfmpfT/UlQf3hG1XnLAWAuk+3qGcgFpytqpszeZhSTTgBRr/rRt9xk12MLbPbp+V
          ahi9eZRVMhUxy01JWs1odAut38FqurtYp/pVVj1hgpOGosTxr+AiJMQV0xzyGJXRrSO2G
          JnRJvLUgcftegwJRj36LPS6ZZ8HYjR8CmMl9rb5hnr6VJxkVtRESoeuo5Ata4OJ9YNl7m
          HKIzOAgpzt5ajpPk0sqx89zvakxuKCAWRoyeqrJaqsAjWoEMlO9SHnFBfGAp8fkafILKU
          oQMxKhQ/WBFAe4eoqto38bM3D6IYXo9lhdY3Bnnj3u9kOxFJWelcCXXpp9e90WGqKpJL4
          N5WyHDBoy4BxU+gN9NXlLd6n8tVxZpNyDSyvKyd/bOkvMbR12guCOt0x2Gq0b8=
        - SGuh9uE7MVSIIXqoiGcXEtPiqDXG4pmjQXDhhfx5ei1TFRPM9U45cMhyLQInYzDe6dPf7
          +Je1gDD0rEvOfkP3NT47SccfwLUh4CeO3ST2JYwViTiniVnFcY2GE0Ks2IC4wORRUspl7
          YtN63QTuAkTxHS/nKDIY4H8bllxlMu6cjEnDCWNaQ4h8rx6LW8yVjhe1ihs9QzaH6Vl1O
          C5Ya8/o+mE2zWgYIAWTw8PWe5DISNXstzPtcSiEvpPscUrHD5+YjR5zVAjBCT1OnlJjL6
          k2vaF7Rwj/wh0WQlURG4RfrXCGXJtWugO2SmiAwQHnKAZyWrE9kbLykaGRf7fo0lmkfoa
          0l8ssOQpVfkh2ngjuqHveeoP88OJb/UePEH4Qa/a1MAehYkoPcz0n4+B6LvgDK04NkRDP
          h4GGOfEzBwoJ2ygTnU6soq0lxAy53XqdNYThIGjV4qSPdR7vP8jSbf5u9ywkuwap1NNVZ
          tN4uPmchJi+faCI3fJCeQCq+Gj+qYE2W8debhdFZUaT9ptNeyuL51+94mwCRV2T/vsS4H
          icWcuTSk3+mTI5zuwf9IXM0MPiGgCcawmVLKPrk7pauy2mc27DJEuCFCXGxqnHvQPWus1
          ISbkYrv42UdGEslU7jZM6Z1lPV9DF99gcMIrt5DFMDxSAlxCwpRa20aZA1dxL8=
        - Lu50FQOeGQTbxX2Pyde+z39phkTF3KaLPGze1sUNgEKXuCBOY3QmTxsyAVHT2MOXFEzVX
          YToX1QRBi05BSfvfr/NB0LA3tBCjcE/bil3cmsoDn4symjE98meXOmNRi08okl5VCXMH7
          6gFx++fWPIcnY2WVdd9Gu14SpWmLEezV1fxd7jH5RAsNQM5XPdDm4nTZkX3u8fewSXYui
          ZoA0D8stZginXQk76I+fYjHvNFp6/OsbSTBl1Su4xANo98R4nKUNbvtjjtX5Io1HIk1Bz
          Ugt5eFcZ/mX6XplPoWHyE+QgbqVqQcdy16PsvrP0P3/AHlHUiqRSjVYHGCbhloHSheQS8
          V5bQigLy5WfQNiPm7g4lYCb9fXsNyswMHtsIQ+BMFz0TeBdYELmZnMFsh4EyeSIlsdlem
          5qViG/dU09nCSv5E4NtQVUZldkBtsQ61S9gslRHGWK45nChjzsxooi6gsZD4aNCsjNuY1
          RO4wn1+WeZ2jMmKpHfDNUmBOikdx8R2D5vzbXhuP5DrULkOmU2BmzqMrqmFlYbdpvQxei
          HVmVVYhQcCZt32uxH+Nx25NQAU4jUsy2Bw8tdp6ln2Q3w3Opmu8OJjekBrBBCj9moaMt8
          elV92YF687Ey7GkLXDqTs/cGKRs4wh2CHoluIkAsWUqfl+s0znRG892u+JfFKc=
