- secret:
    name: site_sflogs
    data:
      fqdn: managesf.sftests.com
      path: /var/www/logs
      ssh_known_hosts: managesf.sftests.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgoQM+01Q9jpT78UkyZQF4Qso/yI9Cp9SY2sGUsusODgDmCFc/BTe48BLCjNoV9KqRIk8D2VV1FX1EuLwGMu5q0V/e0craegKafWx+/F9GKWVE/e1X3QcqIF76LAG5XcYCzUV9G44FdeOIUJfRvaxI1dxww2AZCMgGxDQBXcf2Oafnr4z/TB6I2CBTm7daLh80jKMXFpmCsq+egRk6C/Uer7wa5pTMbgsQDc8chY7zVUOElnjvNlwZmKVTGRf4WULDFA2Tr24SJs7kv0PdT21PeoB+v31qEsLwTmbIWTqFWi8J1Gj6GEhD1CzxmI8aAQLPAwzDJs8zXiL1OwWWU3RX
      ssh_username: loguser
      ssh_private_key: !encrypted/pkcs1-oaep
        - r9UbauUhQZ9Ch6XSu+cCOws/UPGQRYqtbJ8Y0IUFpIRsyULPf5FnJLD4am+3vl3tACyO5
          /eqjggMLGZD9JrpVZmUwA0nfqwNtGmzYTDqzxNRS/KLY2irLw94PSrKYb5Yej156Zju9Z
          p9qrZiMLU+qEhI0YN+kLUFNbK18Um6eNYQ4LVR6axNwpiQYY0YxJ9tXRNosJDVcpPEfKn
          Qy88TE2U5Em6qkgdyAByXIk8WSUoLk/dAZw0a5pVetEgnbjQoobxVSrAQyLczUuhRwBwy
          wazCv5Eh+0tQS0XU1aw9OfrkQdl8eZgijNXaEk6e/2YtZE+IfKqX6AhPdCP7ydaIB3nEw
          +1DijU7ZlapBAlcwGb9VdcAnuV8Dpr9oivZNru1XaaWFFQAdvcgAFYVaRk/zXrVeaqxEQ
          QMrZHlpxXzuLCy6JJgmx1JVA2nKwPQSaNXa/ajuebP+JzCFlyQOG/KSDJ7fIm0+TTSDaj
          uVVC5mwuo/zD/t2/Zq+0gY9u9g2PISYiriMg8IF//uw1Az2qpOMwEQko/TX95KqAFB6al
          SZDeFvU922MykXXWYbUIeDknR5HR9wtA/sCLCvoqzO3fWzuT5r44cifzdmSy+NhtjR2up
          8DdGW5Q3ea1fY7T0/j0Vz4XI2nLJ6BF4NHB08SIbcvter9hdIea+0CX3VRxlyI=
        - qtAw8miQXszpUV9uIpYWv+9eqqJC620C9AWewaOWemeUVT6oAw7lnK+ybGwDHgAP8XrZd
          gk4sYfbmrXOZ8YOAJurUdhcfOOWoBOfi6CXSjnoRKksOhI0ERQmhkFuUmiaGHTGOsd8MU
          A+ffcXFCGouNt6tfnGaImrulotkbQiT8DPXsLr2J+VfT2emtsmIkpWC0N/hlh6iEYwMOp
          N4QR8adRFo9G2E/AVkzO47818MXUMI/Gzn47Vr9dvCPfgg1gb1cKDH4BtuXYIowEpuKhu
          bfl5Dzs1nxeexxs+EgsH/I1tDpFArj0kSyuWkmsm1h79ggky7oA2I5m1BFdGB/JoRRVfW
          UQ0u8Rn4+36kSy6ISzLS7Ywl0zcT9AdrPloDQFQK2vGGHQFIO1To24sKr3wEHOx9P8Xwh
          1JuJp7I4Fj0YLiyolT9SghkPu82l69yiMrC/fTB4T5XkgjexTw+9ezTJCYIxvWoYA8pMU
          bf8LyfloAgzIuKMoA8GipLV/LtFNqucRgClaJgfSrpS4gjKJ/t2LXuvggk2ZlDBrRANUy
          SZQaAUV07w3DK3LqwuXq4XE/D+XD19StdlH7lI7YcVLDccspzYZqzNyT1nrOOikjVY0OO
          BT73/kIHQfaQ1C7d4jOQd4m7IzCHeUZ7eFJ0LjkOdjmaTtGpzNyc7d7XMzQ6eA=
        - B5f1jAO9CSTwKametWhMabYV8vraas7E1io0Exn/zfJqljWRmkUY4rBgOKXOoamYyQESx
          BZPTVsm72dut5KfYUTktwbaiv/0pw8ksqK5o1GiNkMkeLO6ZV+2UJL5EshHYH18b3Zy6n
          96U61qNxLRQe1Yc267ilJeGbthy8gAmBoODKaD/FnFcAVla0XFI9s6yke7wWqEPZndyPI
          MZdceUsh7h8u+LB/LFxOGsuQfO1sjSTySe0xOYRp4XSmcqnEuu6vb0b+gl6aofvk0oOU6
          c8SZ/q00D6qOJu/PnjW6hvzIX/7/S8kG3D0PjUJeqMAM8pAjjXMorPfD2AfMYFY0eCTQK
          r4pO6T8PXovXS25WVuzk404B9rr7T1JAsx6EXKrMz//gMwDV6CJnUlKP1ha5HSUTaeKjx
          H/z7CCr33vuZT0uvtNmYQPmgHIZX7cPVYOJJ9wOVSHlwuC14mgY1Ki0dAXZWnxu9OgXeg
          EecvvcZcoZl9lsgYNiVE3v1s0Crh6cMV6oQggl58GU0/QopKeQq4se/j3JYD00oL1SZ05
          mfk4vOqASkXPirAe5kjF48lCRXNLlAk6+C2gtU99pBXSgU5L6NAZ4BSM/3YKl5U7UIOgL
          qgT2awww7RZv2rXvgDsqZW3EkaPSvF67IkYrc0g9F8LpMbM5yp8tZATLPuM57I=
        - PqXIO/gNQur7zQa01ROKenZq5ehDVylXQWsjHDy+fBoWe4kpBpQJGk/6IyBsQEFzR3N1z
          xlfyuWc/ZTNJEN96Ui28VFcrxiIy3clLkzRC/udFoKpyIjfMzpM42oljDoYIlJKuLlWXC
          GV0Fz3knkohsEMd0RG9ZcTU8JIYkvRgPA+EnYv3/ZiZR+XmVmEmnl970qWk3FYJhJ7pcs
          Vh9r79pXDO/2uo7GSvJKVuWP0isSym3Dt4WDntmFYUVvfxtC0vPU0I7y4qIethrCRNG8x
          rTQbKYNLDgxMmcm85bxZqIB+iPLoFg1PJLWm+kmupGAPFgYxCGOVpcOjWdqLHusW0Yysc
          DSaS4zBp7Q8p71iCnAzYgXFHbYP0tg/eqmcoIaoFmoG6if4FZdKSCsGx1xiSnwtT3SwhV
          Jq0bFcHRWRWaDVzJr7jM6iKEx1b5T9tDjW77/Cll0D9UiAdXIr22ZqLhwLUu05KIDPh/9
          UBJVnjebK2nlixbbKYp/XMkYpfuZgpZ0PwSUSJpItucahzxRg9t80H84jtQFrh8Eb8qxR
          e1xcjgnhHybR9cw9R5VziFcC4Ku/P6H7xLI4CiJrZjAF4UFlS7+ALGuJLlj+jEGAhBJtD
          ZHxFQS7JYdI3N+CF4G+BIIe4r6zMg61gY/Za/IQfzpH7J7dHh8m2bMvfla+jAE=
