---
- project:
    name: openstack/packstack-distgit
    check:
      jobs:
        - dlrn-build
    gate:
      jobs:
        - noop
    post:
      jobs:
        - dlrn-build
        - dlrn-publish:
            dependencies:
              - dlrn-build

- project:
    name: javierpena/packstack
    github-post:
      jobs:
        - dlrn-build
        - dlrn-publish:
            dependencies:
              - dlrn-build
