- secret:
    name: dlrnapi_passwd
    data:
      password: !encrypted/pkcs1-oaep
        - YQ+exQkUphN6JyvYorvtTRrk8xj17A83gvZZRATwkMGAnjUJZlSUwUlp7heHgcUacmz5w
          BplLaG9Xo844V6IS1Rn/wOhCFZ6VpSlVhBo3Eo/jfuP5ZLKV0H34u9R8J4VsdTFpkU1DS
          Q+woyw07GVEa5GHyZYIMaMBTk7Mgx4sn1NISFjYjSRzJUWXDjetKJcHINrQXyChZSMUMn
          dVrheWBzPr/hqlQaogPJWerlAKXurZgueAUxEGgsVMy3p/OAIafid+qEhpjB+jqwEHXPu
          c3Z7mwHLBoG8UpUiFQXmOBLOhmm1iU6SnTNUk3KPTJq9VlM7/BMbXCh1b+6c/fxXpRizF
          0X4b7BpazCNBv7Z29g4ottF0bkc9yADJ6tsLnsfFFPjviJLFbOrsaSd+hcbs2WKSIQknP
          8+zk6hMF6D1x3fcHX0F1qblowYPEb9/NwLWtz7PXHT9fAw0zdK3UWTEjw+jBbMyVy07cw
          lhXe6NhpsSQ+3DUy/zjSQC6/gPwS1TAez5WW8zs+9XXlu7yc4MEPB+d0Xcm3aYqyP7pHN
          LDeomrzQg6i44eU1zdDGoUArgbLnnIJsuq1Omydx9RnZjYfMffIWLFWtXEgPD9t47E/le
          RJgNAiS2lcmnhZ8KPdebeABvSOSQ7+H5BZQAU3zJcZH52DQcQKSiyRaXNiGlXE=
