---
diskimages:
  - name: dib-centos-7
    formats:
      - raw
    username: zuul-worker
    elements:
      - centos-minimal
      - nodepool3-minimal
      - sf-zuul3-worker
      - zuul-worker-user
      - rpm-factory
      - ansible
      - common-packages
      - sf-ci-packages

labels:
 - name: centos7
   min-ready: 1
 - name: dib-centos-7
   min-ready: 1

providers: 
  - name: static-rack
    driver: static
    pools:
      - name: main
        nodes:
          - name: 38.145.34.9
            labels: centos7
            host-key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZIS8uoHMledZZ7WwAixMAvoTealHUM4GZz2K4MCR/4'
            timeout: 15
            ssh-port: 22
            username: centos
            max-parallel-jobs: 2

  - name: rdocloud
    cloud: rdocloud
    clean-floating-ips: true
    image-name-format: '{image_name}-{timestamp}'
    boot-timeout: 120
    rate: 1.0
    diskimages:
      - name: dib-centos-7
    pools:
      - name: main
        max-servers: 3
        labels:
          - name: dib-centos-7
            min-ram: 4000
            diskimage: dib-centos-7
            flavor-name: m1.medium

