ansible-lint:
bridge-utils:
curl:
# firefox:
expect:
rpm-sign:
gcc:
git:
graphviz:
GitPython:
iproute:
java:
libffi-devel:
libpcap-devel:
libseccomp-devel:
libselinux-python:
libxml2-devel:
libxslt-devel:
lsof:
make:
mariadb-devel:
net-tools:
openldap-devel:
openssl:
openssl-devel:
patch:
pigz:
pycrypto:
python-alembic:
python-babel:
python-cffi:
python-crypto:
python-cryptography:
python-daemon:
python-devel:
python-extras:
python-flake8:
python-gear:
python-glob2:
python-jinja2:
python-magic:
python2-markupsafe:
python-nose:
python-paramiko:
python-paste:
python-pip:
python-prettytable:
python-requests:
python-setuptools:
python-six:
python-sphinx:
python-sphinx_rtd_theme:
python-sqlalchemy:
python-statsd:
python-tox:
python-virtualenv:
python2-jmespath:
python2-mock:
python2-twine:
python-voluptuous:
python-webob:
pytz:
PyYAML:
readline-devel:
redhat-lsb-core:
redhat-rpm-config:
rpmdevtools:
ruby-devel:
rubygems:
screen:
systemd-devel:
systemd-python:
unzip:
wget:
Xvfb:
yamllint:
yum-plugin-priorities:
zlib-devel:
